//
// File generated by rootcint at Fri Jan  9 22:16:55 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIincludedIDictionary_DmpEvtBgoPIDVar
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dictionary_DmpEvtBgoPIDVar.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmpEvtBgoPIDVar_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtBgoPIDVar(void *p = 0);
   static void *newArray_DmpEvtBgoPIDVar(Long_t size, void *p);
   static void delete_DmpEvtBgoPIDVar(void *p);
   static void deleteArray_DmpEvtBgoPIDVar(void *p);
   static void destruct_DmpEvtBgoPIDVar(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtBgoPIDVar*)
   {
      ::DmpEvtBgoPIDVar *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtBgoPIDVar >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtBgoPIDVar", ::DmpEvtBgoPIDVar::Class_Version(), "./include/DmpEvtBgoPIDVar.h", 18,
                  typeid(::DmpEvtBgoPIDVar), DefineBehavior(ptr, ptr),
                  &::DmpEvtBgoPIDVar::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtBgoPIDVar) );
      instance.SetNew(&new_DmpEvtBgoPIDVar);
      instance.SetNewArray(&newArray_DmpEvtBgoPIDVar);
      instance.SetDelete(&delete_DmpEvtBgoPIDVar);
      instance.SetDeleteArray(&deleteArray_DmpEvtBgoPIDVar);
      instance.SetDestructor(&destruct_DmpEvtBgoPIDVar);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtBgoPIDVar*)
   {
      return GenerateInitInstanceLocal((::DmpEvtBgoPIDVar*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtBgoPIDVar*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmpEvtBgoPIDVar::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtBgoPIDVar::Class_Name()
{
   return "DmpEvtBgoPIDVar";
}

//______________________________________________________________________________
const char *DmpEvtBgoPIDVar::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoPIDVar*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtBgoPIDVar::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoPIDVar*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtBgoPIDVar::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoPIDVar*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtBgoPIDVar::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtBgoPIDVar*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmpEvtBgoPIDVar::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtBgoPIDVar.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtBgoPIDVar::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtBgoPIDVar::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtBgoPIDVar::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtBgoPIDVar.
      TClass *R__cl = ::DmpEvtBgoPIDVar::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fE_LB", (void*)&fE_LB);
      R__insp.InspectMember("map<int,m_EnergiesInLayer>", (void*)&fE_LB, "fE_LB.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fRMS2[14]", fRMS2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fFValue[14]", fFValue);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTotalE", &fTotalE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPre_Direction", &fPre_Direction);
      R__insp.InspectMember(fPre_Direction, "fPre_Direction.");
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtBgoPIDVar(void *p) {
      return  p ? new(p) ::DmpEvtBgoPIDVar : new ::DmpEvtBgoPIDVar;
   }
   static void *newArray_DmpEvtBgoPIDVar(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtBgoPIDVar[nElements] : new ::DmpEvtBgoPIDVar[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtBgoPIDVar(void *p) {
      delete ((::DmpEvtBgoPIDVar*)p);
   }
   static void deleteArray_DmpEvtBgoPIDVar(void *p) {
      delete [] ((::DmpEvtBgoPIDVar*)p);
   }
   static void destruct_DmpEvtBgoPIDVar(void *p) {
      typedef ::DmpEvtBgoPIDVar current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtBgoPIDVar

namespace ROOT {
   void maplEintcOdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEintcOdoublegR_Dictionary();
   static void *new_maplEintcOdoublegR(void *p = 0);
   static void *newArray_maplEintcOdoublegR(Long_t size, void *p);
   static void delete_maplEintcOdoublegR(void *p);
   static void deleteArray_maplEintcOdoublegR(void *p);
   static void destruct_maplEintcOdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<int,double>*)
   {
      map<int,double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<int,double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<int,double>", -2, "/usr/local/software/root_v5.34/cint/cint/lib/prec_stl/map", 63,
                  typeid(map<int,double>), DefineBehavior(ptr, ptr),
                  0, &maplEintcOdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(map<int,double>) );
      instance.SetNew(&new_maplEintcOdoublegR);
      instance.SetNewArray(&newArray_maplEintcOdoublegR);
      instance.SetDelete(&delete_maplEintcOdoublegR);
      instance.SetDeleteArray(&deleteArray_maplEintcOdoublegR);
      instance.SetDestructor(&destruct_maplEintcOdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<int,double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<int,double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEintcOdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<int,double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEintcOdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,double> : new map<int,double>;
   }
   static void *newArray_maplEintcOdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,double>[nElements] : new map<int,double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEintcOdoublegR(void *p) {
      delete ((map<int,double>*)p);
   }
   static void deleteArray_maplEintcOdoublegR(void *p) {
      delete [] ((map<int,double>*)p);
   }
   static void destruct_maplEintcOdoublegR(void *p) {
      typedef map<int,double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<int,double>

namespace ROOT {
   void maplEintcOmaplEintcOdoublegRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEintcOmaplEintcOdoublegRsPgR_Dictionary();
   static void *new_maplEintcOmaplEintcOdoublegRsPgR(void *p = 0);
   static void *newArray_maplEintcOmaplEintcOdoublegRsPgR(Long_t size, void *p);
   static void delete_maplEintcOmaplEintcOdoublegRsPgR(void *p);
   static void deleteArray_maplEintcOmaplEintcOdoublegRsPgR(void *p);
   static void destruct_maplEintcOmaplEintcOdoublegRsPgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<int,map<int,double> >*)
   {
      map<int,map<int,double> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<int,map<int,double> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<int,map<int,double> >", -2, "/usr/local/software/root_v5.34/cint/cint/lib/prec_stl/map", 63,
                  typeid(map<int,map<int,double> >), DefineBehavior(ptr, ptr),
                  0, &maplEintcOmaplEintcOdoublegRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(map<int,map<int,double> >) );
      instance.SetNew(&new_maplEintcOmaplEintcOdoublegRsPgR);
      instance.SetNewArray(&newArray_maplEintcOmaplEintcOdoublegRsPgR);
      instance.SetDelete(&delete_maplEintcOmaplEintcOdoublegRsPgR);
      instance.SetDeleteArray(&deleteArray_maplEintcOmaplEintcOdoublegRsPgR);
      instance.SetDestructor(&destruct_maplEintcOmaplEintcOdoublegRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<int,map<int,double> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<int,map<int,double> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEintcOmaplEintcOdoublegRsPgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<int,map<int,double> >*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEintcOmaplEintcOdoublegRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,map<int,double> > : new map<int,map<int,double> >;
   }
   static void *newArray_maplEintcOmaplEintcOdoublegRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<int,map<int,double> >[nElements] : new map<int,map<int,double> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEintcOmaplEintcOdoublegRsPgR(void *p) {
      delete ((map<int,map<int,double> >*)p);
   }
   static void deleteArray_maplEintcOmaplEintcOdoublegRsPgR(void *p) {
      delete [] ((map<int,map<int,double> >*)p);
   }
   static void destruct_maplEintcOmaplEintcOdoublegRsPgR(void *p) {
      typedef map<int,map<int,double> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<int,map<int,double> >

/********************************************************
* ./include/Dictionary_DmpEvtBgoPIDVar.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtBgoPIDVar();

extern "C" void G__set_cpp_environmentDictionary_DmpEvtBgoPIDVar() {
  G__cpp_reset_tagtableDictionary_DmpEvtBgoPIDVar();
}
#include <new>
extern "C" int G__cpp_dllrevDictionary_DmpEvtBgoPIDVar() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmpEvtBgoPIDVar */
static int G__Dictionary_DmpEvtBgoPIDVar_455_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtBgoPIDVar* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtBgoPIDVar[n];
     } else {
       p = new((void*) gvp) DmpEvtBgoPIDVar[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtBgoPIDVar;
     } else {
       p = new((void*) gvp) DmpEvtBgoPIDVar;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtBgoPIDVar*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtBgoPIDVar*) G__getstructoffset())->LoadFrom((DmpEvtBgoPIDVar*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtBgoPIDVar::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoPIDVar::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtBgoPIDVar::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtBgoPIDVar::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtBgoPIDVar*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoPIDVar::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtBgoPIDVar::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtBgoPIDVar::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtBgoPIDVar_455_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtBgoPIDVar::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtBgoPIDVar_455_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtBgoPIDVar* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtBgoPIDVar(*(DmpEvtBgoPIDVar*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtBgoPIDVar G__TDmpEvtBgoPIDVar;
static int G__Dictionary_DmpEvtBgoPIDVar_455_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtBgoPIDVar*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtBgoPIDVar*) (soff+(sizeof(DmpEvtBgoPIDVar)*i)))->~G__TDmpEvtBgoPIDVar();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtBgoPIDVar*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtBgoPIDVar*) (soff))->~G__TDmpEvtBgoPIDVar();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtBgoPIDVar_455_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtBgoPIDVar* dest = (DmpEvtBgoPIDVar*) G__getstructoffset();
   *dest = *(DmpEvtBgoPIDVar*) libp->para[0].ref;
   const DmpEvtBgoPIDVar& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmpEvtBgoPIDVar */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDictionary_DmpEvtBgoPIDVar {
 public:
  G__Sizep2memfuncDictionary_DmpEvtBgoPIDVar(): p(&G__Sizep2memfuncDictionary_DmpEvtBgoPIDVar::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDictionary_DmpEvtBgoPIDVar::*p)();
};

size_t G__get_sizep2memfuncDictionary_DmpEvtBgoPIDVar()
{
  G__Sizep2memfuncDictionary_DmpEvtBgoPIDVar a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDictionary_DmpEvtBgoPIDVar() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar))) {
     DmpEvtBgoPIDVar *G__Lderived;
     G__Lderived=(DmpEvtBgoPIDVar*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar),G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDictionary_DmpEvtBgoPIDVar() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,double>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,double,less<int> >",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("m_EnergiesInLayer",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar));
   G__setnewtype(-1,"key: bar ID(0~21)",0);
   G__search_typename2("map<int,m_EnergiesInLayer>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,map<int,double,less<int>,allocator<pair<const int,double> > > >",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,map<int,double,less<int>,allocator<pair<const int,double> > >,less<int> >",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmpEvtBgoPIDVar */
static void G__setup_memvarDmpEvtBgoPIDVar(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar));
   { DmpEvtBgoPIDVar *p; p=(DmpEvtBgoPIDVar*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fE_LB)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR),G__defined_typename("map<int,m_EnergiesInLayer>"),-1,1,"fE_LB=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fRMS2)-(long)(p)),100,0,0,-1,-1,-1,1,"fRMS2[14]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fFValue)-(long)(p)),100,0,0,-1,-1,-1,1,"fFValue[14]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fTotalE)-(long)(p)),100,0,0,-1,-1,-1,1,"fTotalE=",0,"MeV");
   G__memvar_setup((void*)((long)(&p->fPre_Direction)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TVector3),-1,-1,1,"fPre_Direction=",0,"provide from other sub-det");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDictionary_DmpEvtBgoPIDVar() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmpEvtBgoPIDVar(void) {
   /* DmpEvtBgoPIDVar */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar));
   G__memfunc_setup("DmpEvtBgoPIDVar",1390,G__Dictionary_DmpEvtBgoPIDVar_455_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__Dictionary_DmpEvtBgoPIDVar_455_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LoadFrom",788,G__Dictionary_DmpEvtBgoPIDVar_455_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "U 'DmpEvtBgoPIDVar' - 0 - r", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtBgoPIDVar_455_0_4, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtBgoPIDVar::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtBgoPIDVar_455_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoPIDVar::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtBgoPIDVar_455_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtBgoPIDVar::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtBgoPIDVar_455_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtBgoPIDVar::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtBgoPIDVar_455_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtBgoPIDVar_455_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoPIDVar::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtBgoPIDVar_455_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtBgoPIDVar::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtBgoPIDVar_455_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtBgoPIDVar::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtBgoPIDVar_455_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtBgoPIDVar::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtBgoPIDVar", 1390, G__Dictionary_DmpEvtBgoPIDVar_455_0_16, (int) ('i'), G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar), -1, 0, 1, 1, 1, 0, "u 'DmpEvtBgoPIDVar' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtBgoPIDVar", 1516, G__Dictionary_DmpEvtBgoPIDVar_455_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtBgoPIDVar_455_0_18, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar), -1, 1, 1, 1, 1, 0, "u 'DmpEvtBgoPIDVar' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDictionary_DmpEvtBgoPIDVar() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDictionary_DmpEvtBgoPIDVar() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDictionary_DmpEvtBgoPIDVar() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar = { "DmpEvtBgoPIDVar" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR = { "map<int,double,less<int>,allocator<pair<const int,double> > >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR = { "map<int,map<int,double,less<int>,allocator<pair<const int,double> > >,less<int>,allocator<pair<const int,map<int,double,less<int>,allocator<pair<const int,double> > > > > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtBgoPIDVar() {
  G__Dictionary_DmpEvtBgoPIDVarLN_TClass.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TBuffer.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMemberInspector.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TObject.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_TVector3.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDictionary_DmpEvtBgoPIDVar() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar),sizeof(DmpEvtBgoPIDVar),-1,292096,(char*)NULL,G__setup_memvarDmpEvtBgoPIDVar,G__setup_memfuncDmpEvtBgoPIDVar);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR);
}
extern "C" void G__cpp_setupDictionary_DmpEvtBgoPIDVar(void) {
  G__check_setup_version(30051515,"G__cpp_setupDictionary_DmpEvtBgoPIDVar()");
  G__set_cpp_environmentDictionary_DmpEvtBgoPIDVar();
  G__cpp_setup_tagtableDictionary_DmpEvtBgoPIDVar();

  G__cpp_setup_inheritanceDictionary_DmpEvtBgoPIDVar();

  G__cpp_setup_typetableDictionary_DmpEvtBgoPIDVar();

  G__cpp_setup_memvarDictionary_DmpEvtBgoPIDVar();

  G__cpp_setup_memfuncDictionary_DmpEvtBgoPIDVar();
  G__cpp_setup_globalDictionary_DmpEvtBgoPIDVar();
  G__cpp_setup_funcDictionary_DmpEvtBgoPIDVar();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary_DmpEvtBgoPIDVar();
  return;
}
class G__cpp_setup_initDictionary_DmpEvtBgoPIDVar {
  public:
    G__cpp_setup_initDictionary_DmpEvtBgoPIDVar() { G__add_setup_func("Dictionary_DmpEvtBgoPIDVar",(G__incsetup)(&G__cpp_setupDictionary_DmpEvtBgoPIDVar)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDictionary_DmpEvtBgoPIDVar() { G__remove_setup_func("Dictionary_DmpEvtBgoPIDVar"); }
};
G__cpp_setup_initDictionary_DmpEvtBgoPIDVar G__cpp_setup_initializerDictionary_DmpEvtBgoPIDVar;

