/********************************************************************
* ./include/Dictionary_DmpEvtBgoPIDVar.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ./include/Dictionary_DmpEvtBgoPIDVar.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_inheritanceDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_typetableDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_memvarDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_globalDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_memfuncDictionary_DmpEvtBgoPIDVar();
extern void G__cpp_setup_funcDictionary_DmpEvtBgoPIDVar();
extern void G__set_cpp_environmentDictionary_DmpEvtBgoPIDVar();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DmpEvtBgoPIDVar.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TClass;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TBuffer;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMemberInspector;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TObject;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_TVector3;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_DmpEvtBgoPIDVar;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__Dictionary_DmpEvtBgoPIDVarLN_maplEintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRcOlesslEintgRcOallocatorlEpairlEconstsPintcOmaplEintcOdoublecOlesslEintgRcOallocatorlEpairlEconstsPintcOdoublegRsPgRsPgRsPgRsPgRsPgR;

/* STUB derived class for protected member access */
